version: '3.1'

services:

  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './volumenes/postgres:/var/lib/mysql'

  microservicios:
    image: compras
    build:
      context: ./microservicios
    restart: always
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/compras?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    depends_on:
      - mysql
